### ISSUE TITLE
内核与编译器

### ISSUE THREAD

**Issue by Efreets** [HougeLangley/xanmod-archlinux#1]
你好，能做一期跨平台编译器工具链的制作吗，我在msys2中编译gcc老是抱错，昨天晚上在RHEL9中编译gcc-11.3也是出错，估计是configure配置有问题，需要在windows中使用gcc工具链，另外还有关于linux5.15lts版本中mutipath tcp不知道实现怎么样了，还有archlinux怎么启用并设置rdma直接内存访问，和ceph块存储在archlinux具体配置问题

**Comment by HougeLangley** [comment]
你好，虽然这个 issue 和目前这个仓库毫无关系，还是建议朋友可以通过别的方式联系我，比方说我的邮箱，TG等等。

我会尝试下,但是不保证一定会弄，现在我主要精力是放在龙芯测试和容器上，可能精力有限，不保证一定会去折腾。
